name: publish

on:
  push:
    branches:
      - main

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install and build
        run: |
          npm install -g tsx
          pnpm install
          tsx scripts/compile.build.ts
          tsx scripts/manifest.build.ts

      - name: Prepare deployment directory
        run: |
          mkdir -p public
          cp -R dist public
          cp manifest.json public

      - name: Deploy to dist branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: public
          target_branch: dist
          commit_message: 'Deploy to dist branch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
